# Generated by Django 5.0.2 on 2024-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
