# Generated by Django 5.0.2 on 2024-04-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коммантарий', 'verbose_name_plural': 'Коммантарии'},
        ),
    ]
